version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/DBChangeDev/CourseEnginever2
permissions:
  - object: /home/ec2-user
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file
hooks:
  BeforeInstall: 
    - location: scripts/install.sh
      runas: root
      timeout: 300
  AfterInstall:
    - location: scripts/npm-install.sh
      runas: root
      timeout: 300
  ApplicationStart:
    - location: scripts/npm-start.sh
      runas: root
      timeout: 80
